[workspace]
members = ["day01", "day02", "day03", "meta"]
resolver = "2"

[workspace.dependencies]
aoc-traits = { git = "https://github.com/dkales/adventofcode2024-leaderboard", rev = "c03be9a25e0b695061a74f4f0e62f59f59e4f507" }
